leftnav:
- identifier: aa716fe0-2a3d-a154-814f-f0163e0ad35d
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: c3b96859-ec22-06b1-92e3-33fb39f84455
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 96cad2db-c5f1-203b-24ae-8a4156e588df
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: b09c88cd-1fcb-43b7-1195-b5a21b766594
  name: Video Lectures
  url: /video_galleries/video-lectures
  weight: 40
- identifier: 202ec6c1-e20d-cfcf-8dc9-e96f045bbdff
  name: Assignments
  url: /pages/assignments
  weight: 50
